packetbeat.interfaces.device: any

# capture only the monitored_net network traffic
packetbeat.capture.filter: "net 172.20.0.0/16"

# Enable Network Flow tracking.
# This is crucial for detecting attacks on encrypted protocols (like SSH) 
# where Packetbeat cannot read the payload, but we still need to track connection volumes.
packetbeat.flows:
  # If no packets are seen for 5s, the flow is considered closed and reported.
  timeout: 5s
  # For long-running connections, report an update every 5s.
  period: 5s

# Application-layer protocol parsers
packetbeat.protocols:
  - type: http
    ports: [80, 8080]
    send_request: true
    send_response: true
    include_body_for: ["application/x-www-form-urlencoded", "application/json"]

  - type: mysql
    ports: [3306]
    max_rows: 100
    max_row_length: 1024
    send_request: true
    send_response: true

  - type: dns
    ports: [53]

output.kafka:
  hosts: ["kafka:9092"]
  topic: "raw.packets"
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  retries: 3
  retry.backoff: 1s

processors:
  - drop_event:
      when:
        or:       
          # 1. Drop internal Kafka/Elasticsearch chatter (if Packetbeat accidentally catches it)
          - equals:
              destination.port: 9092 # Kafka
          - equals:
              destination.port: 9200 # Elasticsearch
              
          # 2. Drop standard Docker/OS background noise (ARP, ICMP)
          - equals:
              network.transport: "icmp"
          
          # 3. Drop mDNS and local discovery noise
          - equals:
              destination.port: 5353
          - contains:
              dns.question.name: ".local"
          - contains:
              dns.question.name: "arpa"