packetbeat.interfaces.device: any

# capture only the monitored_net network traffic
packetbeat.capture.filter: "net 172.20.0.0/16"

packetbeat.protocols:
  - type: http
    ports: [80, 8080]
    send_request: true
    send_response: true
    include_body_for: ["application/x-www-form-urlencoded", "application/json"]


  - type: dns
    ports: [53]

output.kafka:
  hosts: ["kafka:9092"]
  topic: "raw.packets"
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  retries: 3
  retry.backoff: 1s

processors:
  - drop_event:
      when:
        or:
          # 1. Drop all DNS traffic (Docker internal resolution creates huge noise)
          - equals:
              network.protocol: "dns"
          - equals:
              destination.port: 53
          
          # 2. Drop internal Kafka/Elasticsearch chatter (if Packetbeat accidentally catches it)
          - equals:
              destination.port: 9092 # Kafka
          - equals:
              destination.port: 9200 # Elasticsearch
              
          # 3. Drop standard Docker/OS background noise (ARP, ICMP)
          - equals:
              network.transport: "icmp"