services:
  detection_engine:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: detection_engine
    environment:
      - APP_LOG_LEVEL=DEBUG
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ELASTIC_HOSTS=http://elasticsearch:9200
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./logs:/app/logs
    depends_on:
      - kafka
      - elasticsearch
    networks:
      - pipeline_net
      - elastic_net
    restart: unless-stopped
