#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

echo "========================================================"
echo "Tearing down SOC Environment..."
echo "========================================================"

cd "$(dirname "$0")/../"

# Check if --wipe flag is passed
WIPE=false
if [ "$1" == "--wipe" ]; then
    WIPE=true
fi

if [ "$WIPE" = true ]; then
    # Ensure the user is running with sudo/root privileges for the wipe command
    if [ "$EUID" -ne 0 ]; then
        echo "ERROR: The --wipe flag requires root privileges to delete persistent data."
        echo "Please run this script with sudo: sudo ./teardown.sh --wipe"
        exit 1
    fi

    echo "WARNING: Wiping all containers, images, AND persistent volumes (Kafka/Elastic data)..."
    # Stop and remove containers, networks, volumes, and built images
    docker compose down -v --rmi all
    
    echo "Cleaning up host bind-mount directories..."
    # Clean up Kafka data
    rm -rf infrastructure/kafka/data/*
    
    # Clean up Elastic data
    rm -rf infrastructure/elastic/elasticsearch/data/*
    
    # Clean up Kibana data
    rm -rf infrastructure/elastic/kibana/data/*
    
    # Clean up local log files generated by the detection engine
    echo "Cleaning up local detection engine logs..."
    rm -rf detection_engine/logs/*.log
else
    echo "Stopping and removing containers and images (preserving data volumes)..."
    
    # Guarded check: Only clear blocklist if nginx_server is currently running
    if docker container inspect -f '{{.State.Running}}' nginx_server >/dev/null 2>&1; then
        echo "Clearing Nginx blocklist..."
        # The '|| true' ensures that if this fails for any reason, it won't break the teardown script due to 'set -e'
        docker exec nginx_server sh -c '> /etc/nginx/conf.d/shared/blocklist.conf && nginx -s reload' || true
    fi
    
    docker compose down --rmi local
fi

echo "========================================================"
echo "Teardown complete."
echo "========================================================"
