#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

echo "========================================================"
echo "Tearing down SOC Environment..."
echo "========================================================"

cd "$(dirname "$0")/../"

# Check if --wipe flag is passed
WIPE=false
if [ "$1" == "--wipe" ]; then
    WIPE=true
fi

if [ "$WIPE" = true ]; then
    echo "WARNING: Wiping all containers, images, AND persistent volumes (Kafka/Elastic data)..."
    # Stop and remove containers, networks, volumes, and built images
    docker compose down -v --rmi all
    
    echo "Cleaning up host bind-mount directories..."
    # Clean up Kafka data
    sudo rm -rf infrastructure/kafka/data/*
    
    # Clean up Elastic data
    sudo rm -rf infrastructure/elastic/elasticsearch/data/*
    
    # Clean up Kibana data
    sudo rm -rf infrastructure/elastic/kibana/data/*
    
    # Clean up local log files generated by the detection engine
    echo "Cleaning up local detection engine logs..."
    rm -rf detection_engine/logs/*.log
else
    echo "Stopping and removing containers and images (preserving data volumes)..."
    docker compose down --rmi local
fi

echo "========================================================"
echo "Teardown complete."
echo "========================================================"
